### ISSUE TITLE
Нужна проверка на null аргументов конструктора

### ISSUE THREAD

**Issue by vanstolyaroff** [KozyrevaSvetlana/Online_Shop#1]
https://github.com/KozyrevaSvetlana/Online_Shop/blob/2054441175093f186519e0499c542c795f5c898d/OnlineShop/OnlineShop.Db/ProductsDbRepository.cs#L15

без проверки на null  и передачи null:
- не соблюдаются инварианты класса.
- будет ошибка в ходе выполнения метода, что затруднит поиск.

**Comment by KozyrevaSvetlana** [comment]
для учебного проекта вполне достаточно и данного варианта
