### ISSUE TITLE
Удаление - плохо, помечать как удаленный - хорошо

### ISSUE THREAD

**Issue by vanstolyaroff** [KozyrevaSvetlana/Online_Shop#2]
https://github.com/KozyrevaSvetlana/Online_Shop/blob/2054441175093f186519e0499c542c795f5c898d/OnlineShop/OnlineShop.Db/ProductsDbRepository.cs#L32

При удалении товара из корзины - связанные заказы потеряют ссылку на него, что приведет к нарушению целостности Б/Д. хорошая практика - помечать товары "удаленными", и не давать их заказывать.

**Comment by KozyrevaSvetlana** [comment]
согласна, для учебного проекта можно оставить, в реальном проекте никаких данных удалять нельзя
