### ISSUE TITLE
Если уж удалять, то одной строкой.

### ISSUE THREAD

**Issue by vanstolyaroff** [KozyrevaSvetlana/Online_Shop#3]
https://github.com/KozyrevaSvetlana/Online_Shop/blob/2054441175093f186519e0499c542c795f5c898d/OnlineShop/OnlineShop.Db/ProductsDbRepository.cs#L33

33 и 32 строку можно объединить, выделив предикат в одну строку. Просто убрать лишнее действие.

**Comment by KozyrevaSvetlana** [comment]
исправлено
