### ISSUE TITLE
Асинхронность

### ISSUE THREAD

**Issue by vanstolyaroff** [KozyrevaSvetlana/Online_Shop#4]
https://github.com/KozyrevaSvetlana/Online_Shop/blob/2054441175093f186519e0499c542c795f5c898d/OnlineShop/OnlineShop.Db/ProductsDbRepository.cs#L30

async Task вместо void позволяет снизить время простаивания потоков пула, что позволит им выполнять другие задачи, увеличивая количество запросов, обрабатываемых приложением. Далее по коду актуально для всех методов.

**Comment by KozyrevaSvetlana** [comment]
давно исправлено
