### ISSUE TITLE
Плохое наименование аргументов.

### ISSUE THREAD

**Issue by vanstolyaroff** [KozyrevaSvetlana/Online_Shop#5]
https://github.com/KozyrevaSvetlana/Online_Shop/blob/2054441175093f186519e0499c542c795f5c898d/OnlineShop/OnlineShop.Db/ProductsDbRepository.cs#L55

SearchWords было бы актуальнее

**Comment by KozyrevaSvetlana** [comment]
исправлено

**Comment by KozyrevaSvetlana** [comment]
переименовано
