### ISSUE TITLE
Неудачная структура данных

### ISSUE THREAD

**Issue by vanstolyaroff** [KozyrevaSvetlana/Online_Shop#6]
https://github.com/KozyrevaSvetlana/Online_Shop/blob/2054441175093f186519e0499c542c795f5c898d/OnlineShop/OnlineShop.Db/ProductsDbRepository.cs#L63

Есть HashSet, он тут более уместен, т.к. хранит только уникальные объекты (не надо делать Distinct)

**Comment by KozyrevaSvetlana** [comment]
исправлено!

**Comment by KozyrevaSvetlana** [comment]
исправлено
