### ISSUE TITLE
Неудачная сигнатура метода

### ISSUE THREAD

**Issue by vanstolyaroff** [KozyrevaSvetlana/Online_Shop#7]
https://github.com/KozyrevaSvetlana/Online_Shop/blob/2054441175093f186519e0499c542c795f5c898d/OnlineShop/OnlineShop.Db/ProductsDbRepository.cs#L61

Есть алгоритмы поиска более удачные. например Like, а еще лучше через полнотекстовый индекс

**Comment by KozyrevaSvetlana** [comment]
Спасибо за все замечания, приму их к сведению и исправлю

**Comment by KozyrevaSvetlana** [comment]
исправлено

**Comment by KozyrevaSvetlana** [comment]
закрыто
